### ISSUE TITLE
Double Check IRC Initial Displacement Formula

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi-rking/optking#19]
When trying to use an IRC to follow a particularly shallow imaginary mode (~52i) with C-OptKing, I repeatedly saw the initial displacement increasing the energy. The displacement in cartesians didn't align with my normal mode, either. The C-OptKing way seems to get its initial displacement by [taking the lowest eigenvector from the internal hessian](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/optking/molecule_irc_step.cc#L290-L291). This will not be the normal mode.

I was able to get my energy to decrease along the C-OptKing IRC by getting the lowest eigenvector from the massweighted internal hessian and operating with G^-1/2. (This seems unusual, as all the other transformations from mass weighted to non-mass-weighted coordinates use G+^1/2. Using G^+1/2 still led to an increase in energy.)

Could you double-check that part of the IRC algorithm when adapting to Python?

**Comment by JonathonMisiewicz** [comment]
Note: There's nothing unusual about needing to operate with G^-1/2 on the gradient. G^+1/2 is correct when you're operating on _displacements_. The gradient transforms covariantly instead of contravariantly, so it transforms as the inverse transpose of G^+1/2. As G is symmetric, the correct gradient transformation rule is G^-1/2... exactly as I found numerically.

**Comment by psi-rking** [comment]
As of now, the IRC code is working.  I made sure that the initial step does follow mass-weighted Hessian.  If the initial Hessian is a stupid diagonal guess, it turns out this makes no difference (which might be part of the reason we didn't catch the problem earlier.  My testing for HOOH showed no detectable change in the converged reaction path points obtained.  If the energy is increasing, it may be the step size is simply too large.
